import type { Student } from "./students-types";

export const students: Student[] = [
  {
    id: "student-001",
    fullName: "Carlos Hernández López",
    code: "AL-001",
    birthDate: "12/03/2011",
    phone: "55581234",
    grade: "Primero básico",
    average: 82,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-002",
    fullName: "María Fernanda López",
    code: "AL-002",
    birthDate: "25/07/2010",
    phone: "51234567",
    grade: "Segundo básico",
    average: 85,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-003",
    fullName: "José Antonio Martínez",
    code: "AL-003",
    birthDate: "08/11/2009",
    phone: "59874521",
    grade: "Primero básico",
    average: 76,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-004",
    fullName: "Ana Sofía Rodríguez",
    code: "AL-004",
    birthDate: "17/01/2011",
    phone: "54671289",
    grade: "Primero básico",
    average: 88,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-005",
    fullName: "Luis Fernando García",
    code: "AL-005",
    birthDate: "04/05/2010",
    phone: "58741236",
    grade: "Segundo básico",
    average: 69,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-006",
    fullName: "Sofía Alejandra Morales",
    code: "AL-006",
    birthDate: "29/09/2009",
    phone: "52369874",
    grade: "Tercero básico",
    average: 89,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-007",
    fullName: "Daniel Alejandro Pérez",
    code: "AL-007",
    birthDate: "14/02/2011",
    phone: "53698741",
    grade: "Primero básico",
    average: 73,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-008",
    fullName: "Valeria Isabel Castillo",
    code: "AL-008",
    birthDate: "21/06/2010",
    phone: "57412369",
    grade: "Segundo básico",
    average: 86,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-009",
    fullName: "Miguel Ángel Ramírez",
    code: "AL-009",
    birthDate: "09/10/2009",
    phone: "56897412",
    grade: "Primero básico",
    average: 78,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-010",
    fullName: "Camila Andrea González",
    code: "AL-010",
    birthDate: "03/04/2011",
    phone: "54123698",
    grade: "Primero básico",
    average: 84,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-011",
    fullName: "Fernando Estuardo Díaz",
    code: "AL-011",
    birthDate: "18/08/2010",
    phone: "58963214",
    grade: "Segundo básico",
    average: 71,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-012",
    fullName: "Lucía Fernanda Herrera",
    code: "AL-012",
    birthDate: "27/12/2009",
    phone: "54789632",
    grade: "Tercero básico",
    average: 91,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-013",
    fullName: "Andrés Eduardo Méndez",
    code: "AL-013",
    birthDate: "11/03/2011",
    phone: "59632147",
    grade: "Primero básico",
    average: 84,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-014",
    fullName: "Isabella María Reyes",
    code: "AL-014",
    birthDate: "30/07/2010",
    phone: "53214789",
    grade: "Segundo básico",
    average: 81,
    gender: "Femenino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-015",
    fullName: "Javier Alejandro Vásquez",
    code: "AL-015",
    birthDate: "06/11/2009",
    phone: "57896321",
    grade: "Tercero básico",
    average: 67,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-016",
    fullName: "Daniela Paola Aguilar",
    code: "AL-016",
    birthDate: "23/01/2011",
    phone: "51478963",
    grade: "Primero básico",
    average: 87,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-017",
    fullName: "Diego Armando López",
    code: "AL-017",
    birthDate: "15/05/2010",
    phone: "56321478",
    grade: "Segundo básico",
    average: 74,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-018",
    fullName: "Gabriela Alejandra Fuentes",
    code: "AL-018",
    birthDate: "02/09/2009",
    phone: "58796314",
    grade: "Tercero básico",
    average: 87,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-019",
    fullName: "Alejandro José Ortiz",
    code: "AL-019",
    birthDate: "20/02/2011",
    phone: "53621479",
    grade: "Primero básico",
    average: 80,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-020",
    fullName: "Natalia Fernanda Cabrera",
    code: "AL-020",
    birthDate: "13/06/2010",
    phone: "57489613",
    grade: "Segundo básico",
    average: 88,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-021",
    fullName: "Sebastián Andrés Castro",
    code: "AL-021",
    birthDate: "28/10/2009",
    phone: "52147896",
    grade: "Primero básico",
    average: 72,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-022",
    fullName: "Paula Andrea Mendoza",
    code: "AL-022",
    birthDate: "07/04/2011",
    phone: "58974123",
    grade: "Primero básico",
    average: 85,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-023",
    fullName: "Mateo Alejandro Rivera",
    code: "AL-023",
    birthDate: "16/08/2010",
    phone: "54712398",
    grade: "Segundo básico",
    average: 77,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-024",
    fullName: "Andrea Lucía Soto",
    code: "AL-024",
    birthDate: "01/12/2009",
    phone: "56398712",
    grade: "Tercero básico",
    average: 95,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-025",
    fullName: "Emilio José Vargas",
    code: "AL-025",
    birthDate: "24/03/2011",
    phone: "59874126",
    grade: "Primero básico",
    average: 68,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-026",
    fullName: "Regina Sofía Salazar",
    code: "AL-026",
    birthDate: "10/07/2010",
    phone: "53269874",
    grade: "Segundo básico",
    average: 86,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-027",
    fullName: "Nicolás Eduardo Flores",
    code: "AL-027",
    birthDate: "19/11/2009",
    phone: "57841269",
    grade: "Tercero básico",
    average: 93,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-028",
    fullName: "Mariana Isabel Rojas",
    code: "AL-028",
    birthDate: "05/01/2011",
    phone: "51496328",
    grade: "Primero básico",
    average: 88,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-029",
    fullName: "Samuel David Guerra",
    code: "AL-029",
    birthDate: "22/05/2010",
    phone: "56987412",
    grade: "Segundo básico",
    average: 75,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-030",
    fullName: "Elías Alejandro Miranda",
    code: "AL-030",
    birthDate: "12/09/2009",
    phone: "58741296",
    grade: "Tercero básico",
    average: 97,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-031",
    fullName: "David Alejandro Escobar",
    code: "AL-031",
    birthDate: "26/02/2011",
    phone: "53698724",
    grade: "Primero básico",
    average: 81,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-032",
    fullName: "Sara Fernanda Monroy",
    code: "AL-032",
    birthDate: "08/06/2010",
    phone: "57412963",
    grade: "Segundo básico",
    average: 83,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-033",
    fullName: "Ángel Estuardo Molina",
    code: "AL-033",
    birthDate: "17/10/2009",
    phone: "52149687",
    grade: "Tercero básico",
    average: 70,
    gender: "Masculino",
    paymentStatus: "Moroso",
  },
  {
    id: "student-034",
    fullName: "Adriana Sofía Pineda",
    code: "AL-034",
    birthDate: "04/04/2011",
    phone: "59876321",
    grade: "Primero básico",
    average: 88,
    gender: "Femenino",
    paymentStatus: "Solvente",
  },
  {
    id: "student-035",
    fullName: "Pablo Andrés Alvarado",
    code: "AL-035",
    birthDate: "31/08/2010",
    phone: "54789621",
    grade: "Primero básico",
    average: 83,
    gender: "Masculino",
    paymentStatus: "Solvente",
  },
];

export const STUDENTS_PER_PAGE = 10;
