import type { Teacher } from "./teachers-types";

export const teachers: Teacher[] = [
  {
    id: "teacher-001",
    fullName: "Roberto Antonio Méndez",
    code: "MT-001",
    birthDate: "18/04/1982",
    phone: "55213478",
    classSubject: "Matemática",
    email: "roberto.mendez@educore.com",
    gender: "Masculino",
  },
  {
    id: "teacher-002",
    fullName: "Claudia Isabel Ramírez",
    code: "MT-002",
    birthDate: "09/09/1985",
    phone: "56891234",
    classSubject: "Comunicación y Lenguaje",
    email: "claudia.ramirez@educore.com",
    gender: "Femenino",
  },
  {
    id: "teacher-003",
    fullName: "Jorge Luis Castillo",
    code: "MT-003",
    birthDate: "27/01/1979",
    phone: "53456789",
    classSubject: "Ciencias Naturales",
    email: "jorge.castillo@educore.com",
    gender: "Masculino",
  },
  {
    id: "teacher-004",
    fullName: "Patricia Alejandra Morales",
    code: "MT-004",
    birthDate: "14/06/1988",
    phone: "57654321",
    classSubject: "Estudios Sociales",
    email: "patricia.morales@educore.com",
    gender: "Femenino",
  },
  {
    id: "teacher-005",
    fullName: "Mario Enrique López",
    code: "MT-005",
    birthDate: "03/12/1981",
    phone: "54127896",
    classSubject: "Inglés",
    email: "mario.lopez@educore.com",
    gender: "Masculino",
  },
  {
    id: "teacher-006",
    fullName: "Gabriela Sofía Herrera",
    code: "MT-006",
    birthDate: "22/02/1990",
    phone: "59981234",
    classSubject: "Computación",
    email: "gabriela.herrera@educore.com",
    gender: "Femenino",
  },
  {
    id: "teacher-007",
    fullName: "Fernando Javier Pérez",
    code: "MT-007",
    birthDate: "11/10/1984",
    phone: "52345678",
    classSubject: "Educación Física",
    email: "fernando.perez@educore.com",
    gender: "Masculino",
  },
  {
    id: "teacher-008",
    fullName: "Lucía Fernanda García",
    code: "MT-008",
    birthDate: "30/07/1987",
    phone: "58765432",
    classSubject: "Artes Plásticas",
    email: "lucia.garcia@educore.com",
    gender: "Femenino",
  },
];

export const TEACHERS_PER_PAGE = 10;
